# Generated by Django 3.2.6 on 2021-08-09 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProfilePic', models.ImageField(upload_to='ProfilePic')),
                ('Name', models.CharField(default='', max_length=50)),
                ('Branch', models.CharField(default='', max_length=30)),
                ('Batch', models.IntegerField(default=0)),
            ],
        ),
    ]
