# Generated by Django 3.2.6 on 2021-08-10 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudentRegistrationApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='ProfilePic',
        ),
    ]
