# Generated by Django 3.2.6 on 2021-08-10 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentRegistrationApp', '0002_remove_registration_profilepic'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='ProfilePic',
            field=models.ImageField(default='', upload_to='ProfilePic'),
        ),
    ]
